### ISSUE TITLE
No "Rremove display from desktop" on Win10

### ISSUE THREAD

**Issue by pc-john** [nvpro-samples/gl_render_vk_ddisplay#2]
Hi! Thanks for very valuable code. One comment: I cannot find "Remove display from desktop" switch on "Advanced display settings". It is not there.

Further investigation revealed following info:
-  I have Windows 10 Pro, version 2004
-  https://www.tenforums.com/tutorials/154973-how-remove-display-desktop-windows-10-a.html suggests that Windows 10 Enterprise or the Windows 10 Pro for Workstations is needed
- https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkAcquireWinrtDisplayNV.html suggests that the switch is available since Windows 10 Pro

Sorry, no more info and no chance for me to verify if the information is correct. I only know that it is not present on my Windows 10.

**Comment by vojtadavid** [comment]
IMHO you need Windows 10 Enterprise or Windows 10 Pro for Workstations editions Windows 10 Pro for Workstations

**Comment by iesser** [comment]
Hi pc-john,

your analysis is correct, certain Windows versions are required, otherwise the feature is not available.

Kind Regards,
  Ingo
