### ISSUE TITLE
vkAcquireWinrtDisplayNV makes the process unkillable after application crash

### ISSUE THREAD

**Issue by vvchyron** [nvpro-samples/gl_render_vk_ddisplay#4]
Hello,
I was previously in contact with original creator of this sample Ingo Esser (and @NeilBickford-NV), but it seems that he is no more maintaining this, so I am writing here...

Like one year ago I was able to to reproduce the logic without any issues, everything was running "super green".

The prolem now seems to be connectd to the "new" added extension `VK_NV_acquire_winrt_display` and call:
VkResult res = pfn_vkAcquireWinrtDisplayNV(m_gpu, m_display.displayKHR);
This change was introduced by @nvmheyer in commit 9d5c5b9acb6434dcad11b01a1e6b1c1118b663bd

If this is presented in the application after the execusion ends (or app crashes) the process become hanging in the task manager being completely unkillable and it is not even possible to restart the machine (restart screen runs forever, only possibility is power off and on).

I am quite confident that this was introduced by using vkAcquireWinrtDisplayNV, because when app is hanging and you go to the Display settings -> Advanced settings (same place where you select the monitor to remove it from usage by OS) the removed monitor is still present there in the rolldown menu, but when you select it, the display settings window crashes...

I tried to solve this issue by adding call:
`VkResult result = pfn_vkReleaseDisplayEXT(_gpu, _display.displayProperties.display);`
to release the display, but without any success.
Should this approach work and should I be able to release the display by this action?

Is there any possibility to release the display back to OS or at last be able to kill it somehow (no taskkill \F by PID works as it is stating instance not found, but I see it in the tasklist though)?

I am afraid that because (probably some API) changes the `vkAcquireWinrtDisplayNV` is necesary now as otherway you are not able to create the swapchain (invalid result without `vkAcquireWinrtDisplayNV` called previously) is it true or is there still some way to avoid it or what is its purpose and why it was not required before?

**Comment by iesser** [comment]
Hi vvchyron,

thank you for your analysis. The sample was missing another call that makes sure that the unkillable-process issue does not come up.
I've just modified the sample, could you give it another try?

Kind Regards,
  Ingo

**Comment by vvchyron** [comment]
@iesser
Hi Ingo,
I was stuck with other issues meanwhile, but it seems from what I tested last days that Your fix introducing the env. variable works as intended and I do not need to power off/on the workstation anymore to be able to operate the display that was previously disconnected from Win OS.

Thanks for support.
